# Generated by Django 4.1 on 2022-09-05 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 7, 11, 44, 431927, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 7, 11, 44, 431890, tzinfo=datetime.timezone.utc)),
        ),
    ]
